<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>RevStackCore.MySQL</PackageId>
    <PackageVersion>2.3.0</PackageVersion>
    <Authors>David Sheets, S. Francis</Authors>
    <Description>MySQL implementation of the RevStackCore Repository Pattern.</Description>
    <PackageProjectUrl>https://github.com/RevStackCore/MySQL.git</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/RevStackCore/MySQL/blob/master/LICENSE</PackageLicenseUrl>
    <PackageIconUrl>https://s3.amazonaws.com/revstack/icons/revstackcore-64x64.png</PackageIconUrl>
    <PackageReleaseNotes>2.3.0: bump MySqlConnector 0.69.2 → 2.3.7 for MySQL 8.4 compatibility (caching_sha2_password)</PackageReleaseNotes>
    <Copyright>Copyright 2019</Copyright>
    <PackageTags>RevStackCore Repository MySQL</PackageTags>	
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DbContext\" />
    <Folder Include="Repository\" />
    <Folder Include="Mappings\" />
    <Folder Include="Extensions\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RevStackCore.SQL.Client" Version="1.2.4" />
    <PackageReference Include="RevStackCore.Pattern.SQL" Version="1.1.2" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
  </ItemGroup>
</Project>
